name: Send Telegram Message

inputs:
  APP_NAME:
    required: true

runs:
  using: 'composite'
  steps:
    - name: Generate Message Info
      id: message
      shell: bash
      run: |
      MESSAGE_INFO="
      Setup bản build mới...
      \n- App: ${{ inputs.APP_NAME }}.
      \n- Môi trường: ${{ env.BUILD_VERSION_LABEL }}.
      \n- Phiên bản: ${{ env.BUILD_VERSION_FULL }}.
      \n- Bản build số: ${{ env.BUILD_VERSION_NUMBER }}.
      \n- Người build: ${{ env.BUILD_ACTOR }}."

    - name: Send Telegram Message
      shell: bash
      run: |
        curl --location "https://api.telegram.org/bot$TELEGRAM_BOT_TOKEN/sendMessage" \
          --header 'Content-Type: application/json' \
          --data '{
              "chat_id": "'$TELEGRAM_GROUP_ID'",
              "reply_to_message_id": "'$TELEGRAM_TOPIC_ID'",
              "text": "'"$1"'"
          }'